name: "Check modified files for Quality"
description: "Check for modified files in specific paths"

outputs:
  changed:
    description: "Whether any specified files have been modified"
    value: ${{ steps.check-modified.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Fetch base branch
      run: git fetch origin ${{ github.base_ref }}
      shell: bash

    - name: Check modified files
      id: check-modified
      run: |
        echo "changed=$(git diff --name-only FETCH_HEAD ${{ github.sha }} | grep -q -E '^(docs/|.github/workflows/quality.yml|.github/composite-actions/check-docs-modified-files/|package.json|.eslintrc.base.json)' && echo true || echo false)" >> $GITHUB_OUTPUT
      shell: bash
