name: "Check modified files for Quality"
description: "Check for modified files in specific paths"

inputs:
  file_patterns:
    description: "Regex patterns of files to check for modifications"
    required: true

outputs:
  changed:
    description: "Whether any specified files have been modified"
    value: ${{ steps.check-modified.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Fetch base branch
      run: git fetch origin ${{ github.base_ref }}
      shell: bash

    - name: Convert comma-separated to regex pattern
      id: convert-pattern
      run: |
        regex_pattern=$(echo "${{ inputs.file_patterns }}" | sed 's/,/|/g')
        echo "regex_pattern=$regex_pattern" >> $GITHUB_ENV
      shell: bash

    - name: Check modified files
      id: check-modified
      run: |
        echo "changed=$(git diff --name-only FETCH_HEAD ${{ github.sha }} | grep -q -E '^(.github/workflows/quality.yml|.github/composite-actions/check-modified-files/|package.json|pnpm-workspace.yaml|turbo.json|${{ env.regex_pattern }})' && echo true || echo false)" >> $GITHUB_OUTPUT
        echo "modified_files=$(git diff --name-only FETCH_HEAD ${{ github.sha }})" >> $GITHUB_OUTPUT
      shell: bash
