name: "Update docs"
description: "Update the documentation sites after the release"

runs:
  using: composite
  steps:
    - name: Fetch latest from origin
      run: git fetch origin
      shell: bash

    - name: Update docs
      run: |
        pnpm gen:docs
        pnpm docs:theme
        pnpm docs:props
        pnpm docs:changelog
        pnpm docs:styled-system
        pnpm docs:contributors
        pnpm docs:search
        pnpm docs:icon-tags
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.BOT_TOKEN }}
        base: main
        commit-message: "ci(changesets): version packages"
        title: "Updated documentation"
        branch: changeset-release/docs
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
