name: Pre-release

on:
  push:
    branches:
      - changeset-release/main
    paths:
      - ".changeset/**"
      - "packages/**"
      - "!packages/**/DOCS.json"
      - "!docs/**"
      - "!.changelog/**"
      - "!CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Update docs
        run: |
          pnpm gen:docs
          pnpm docs:theme
          pnpm docs:props
          git add .
          git diff --staged --exit-code || git commit -m 'ci(component): updated component'

          pnpm changelog:ci
          pnpm docs:changelog
          git add .
          git diff --staged --exit-code || git commit -m 'ci(changelog): updated changelog'

          pnpm docs:css
          git add .
          git diff --staged --exit-code || git commit -m 'ci(css): updated css'

          pnpm docs:contributors
          git add .
          git diff --staged --exit-code || git commit -m 'ci(contributors): updated contributors'

          pnpm docs:search
          git add .
          git diff --staged --exit-code || git commit -m 'ci(docs): updated docs'

          git push
