name: Reviwers Pull Requests

on:
  pull_request:
    types: [review_requested, review_request_removed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_REVIEWS_WEBHOOK_URL: ${{ secrets.DISCORD_REVIEWS_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Notification requested reviewer
        if: ${{ github.event.action == 'review_requested' }}
        run: pnpm notification:reviewer ${{ github.event.pull_request.number }} --requested=${{ github.event.requested_reviewer.login }}

      - name: Notification removed reviewer
        if: ${{ github.event.action == 'review_request_removed' }}
        run: pnpm notification:reviewer ${{ github.event.pull_request.number }} --removed=${{ github.event.requested_reviewer.login }}
